Version = 1;
Make: "LG";
Model: "V30 (joan)";

Rear: {
    SensorDriver: "imx351 6-0010";
    BridgeDriver: "qcom-camss";

    Modes: (
        {
            Width: 2328;
            Height: 1744;
            Rate: 30;
            Format: "RGGB10P";
            Rotate: 0;
            Transfer: "srgb";

            Pipeline: (
                {Type: "Link", From: "imx351 6-0010", FromPad: 0, To: "msm_csiphy0", ToPad: 0},
                {Type: "Link", From: "msm_csiphy0", FromPad: 1, To: "msm_csid0", ToPad: 0},
                {Type: "Link", From: "msm_csid0", FromPad: 1, To: "msm_ispif0", ToPad: 0},
                {Type: "Link", From: "msm_ispif0", FromPad: 1, To: "msm_vfe0_rdi0", ToPad: 0},

                {Type: "Mode", Entity: "imx351 6-0010"},
                {Type: "Mode", Entity: "msm_csiphy0"},
                {Type: "Mode", Entity: "msm_csid0"},
                {Type: "Mode", Entity: "msm_ispif0"},
                {Type: "Mode", Entity: "msm_vfe0_rdi0"}
            );
        }
    );
};

RearWide: {
    SensorDriver: "s5k3m3 7-002d";
    BridgeDriver: "qcom-camss";

    Modes: (
        {
            Width: 2080;
            Height: 1172;
            Rate: 30;
            Format: "GRBG10P";
            Rotate: 180;
            Transfer: "srgb";

            Pipeline: (
                {Type: "Link", From: "s5k3m3 7-002d", FromPad: 0, To: "msm_csiphy1", ToPad: 0},
                {Type: "Link", From: "msm_csiphy1", FromPad: 1, To: "msm_csid1", ToPad: 0},
                {Type: "Link", From: "msm_csid1", FromPad: 1, To: "msm_ispif1", ToPad: 0},
                {Type: "Link", From: "msm_ispif1", FromPad: 1, To: "msm_vfe0_rdi1", ToPad: 0},

                {Type: "Mode", Entity: "s5k3m3 7-002d"},
                {Type: "Mode", Entity: "msm_csiphy1"},
                {Type: "Mode", Entity: "msm_csid1"},
                {Type: "Mode", Entity: "msm_ispif1"},
                {Type: "Mode", Entity: "msm_vfe0_rdi1"}
            );
        }
    );
};

Front: {
    SensorDriver: "hi553 4-0020";
    BridgeDriver: "qcom-camss";

    Modes: (
        {
            Width: 2560;
            Height: 1440;
            Rate: 30;
            Format: "GBRG10P";
            Rotate: 0;
            Transfer: "srgb";

            Pipeline: (
                {Type: "Link", From: "hi553 4-0020", FromPad: 0, To: "msm_csiphy2", ToPad: 0},
                {Type: "Link", From: "msm_csiphy2", FromPad: 1, To: "msm_csid2", ToPad: 0},
                {Type: "Link", From: "msm_csid2", FromPad: 1, To: "msm_ispif2", ToPad: 0},
                {Type: "Link", From: "msm_ispif2", FromPad: 1, To: "msm_vfe0_rdi2", ToPad: 0},

                {Type: "Mode", Entity: "hi553 4-0020"},
                {Type: "Mode", Entity: "msm_csiphy2"},
                {Type: "Mode", Entity: "msm_csid2"},
                {Type: "Mode", Entity: "msm_ispif2"},
                {Type: "Mode", Entity: "msm_vfe0_rdi2"}
            );
        }
    );
};
